
import React from 'react';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { BrandingConfig } from '@/services/export/types';

interface ReportBrandingSettingsProps {
  brandingConfig: BrandingConfig | undefined;
  onBrandingConfigChange: <K extends keyof BrandingConfig>(
    field: K,
    value: BrandingConfig[K]
  ) => void;
}

export function ReportBrandingSettings({ brandingConfig, onBrandingConfigChange }: ReportBrandingSettingsProps) {
  return (
    <div className="space-y-4">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="space-y-2">
          <Label htmlFor="company">Company Name</Label>
          <Input
            id="company"
            value={brandingConfig?.companyName || ''}
            onChange={(e) => onBrandingConfigChange('companyName', e.target.value)}
            placeholder="Your Company Name"
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor="primaryColor">Primary Color</Label>
          <Input
            id="primaryColor"
            type="color"
            value={brandingConfig?.primaryColor || '#3B82F6'}
            onChange={(e) => onBrandingConfigChange('primaryColor', e.target.value)}
          />
        </div>
      </div>
      
      <div className="space-y-2">
        <Label htmlFor="footer">Footer Text</Label>
        <Input
          id="footer"
          value={brandingConfig?.footerText || ''}
          onChange={(e) => onBrandingConfigChange('footerText', e.target.value)}
          placeholder="Generated by Webinar Wise Analytics"
        />
      </div>
    </div>
  );
}
