// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgajnzldkfpvcuofjxom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnYWpuemxka2ZwdmN1b2ZqeG9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MjkzOTksImV4cCI6MjA2NjQwNTM5OX0.Czjd8aGqWo31lFYwzGz0RgPBwJxNK3Fr20Mbj6Jv0dA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);